# EE569 Homework Assignment #1
# Name : Amruta Kulkarni
# USC ID : 6914-9708-27
# email : arkulkar@usc.edu
# Date : 20 Sept 2015
# Compiled on Mac with g++

all:
	g++ -o run main_BM3D.cpp
	@echo "compiling the code for denoising using BM3D filter"
	@echo "usage : ./run inputImageName outputImageName1 outputImageName2 outputImageName3 "
	@echo "example : ./run peppers_noisy.raw redNoisyPeppers.raw greenNoisyPeppers.raw blueNoisyPeppers.raw"
	./run peppers_noisy.raw redNoisyPeppers.raw greenNoisyPeppers.raw blueNoisyPeppers.raw
	@echo "NOW COPY THE 3 IMAGES THAT HAVE BEEN GENERATED ABOVE INTO MATLAB AND THEN RUN THE BM3D_code.m FILE THAT IS PROVIDED"