# EE569 Homework Assignment #1
# Name : Amruta Kulkarni
# USC ID : 6914-9708-27
# email : arkulkar@usc.edu
# Date : 20 Sept 2015
# Compiled on Mac with g++

all:
	g++ -o run main_mixed_noise.cpp
	@echo "compiling the code for denoising"
	@echo "usage : ./run inputImageName outputImageName inputImage"
	@echo "example : ./run peppers_noisy.raw noiseFreePepper.raw peppers.raw"
	@echo "PLEASE ENTER YOUR FILE NAMES AS SHOWN IN THE ABOVE EXAMPLE"