# EE569 Homework Assignment #1
# Name : Amruta Kulkarni
# USC ID : 6914-9708-27
# email : arkulkar@usc.edu
# Date : 20 Sept 2015
# Compiled on Mac with g++

all:
	g++ -o run main_coliseum.cpp
	@echo "compiling the code for Coliseum oil painting"
	@echo "usage : ./run inputImageName outputImageName1 outputImageName2"
	@echo "example : ./run coliseum.raw quantized_Coliseum.raw oilPainting_coliseum.raw"
	@echo "PLEASE ENTER YOUR FILE NAMES AS SHOWN IN THE ABOVE EXAMPLE"