# EE569 Homework Assignment #1
# Name : Amruta Kulkarni
# USC ID : 6914-9708-27
# email : arkulkar@usc.edu
# Date : 20 Sept 2015
# Compiled on Mac with g++

all:
	g++ -o run main_bilinear_demosaicing.cpp
	@echo "compiling the code for bilinear demosaicing"
	@echo "usage : ./run inputImageName outputImageName"
	@echo "example : ./run parrot_CFA.raw parrot_bilinear_Demosaiced.raw"
	@echo "PLEASE ENTER YOUR FILE NAMES AS SHOWN IN THE ABOVE EXAMPLE"