# EE569 Homework Assignment #1
# Name : Amruta Kulkarni
# USC ID : 6914-9708-27
# email : arkulkar@usc.edu
# Date : 20 Sept 2015
# Compiled on Mac with g++

all:
	g++ -o run main_histogram_equalization_transfer.cpp
	@echo "compiling the code for Histogram equalization"
	@echo "usage : ./run inputImageName outputImageNametype"
	@echo "example : ./run jet.raw transfer_function_jet.raw"
	@echo "PLEASE ENTER YOUR FILE NAMES AS SHOWN IN THE ABOVE EXAMPLE"