# EE569 Homework Assignment #1
# Name : Amruta Kulkarni
# USC ID : 6914-9708-27
# email : arkulkar@usc.edu
# Date : 20 Sept 2015
# Compiled on Mac with g++

all:
	g++ -o run main_resizing.cpp
	@echo "compiling the code"
	@echo "usage : ./run inputImageName outputImageName bytesPerPixel size"
	@echo "example : ./run the_starry_night.raw bilinearly_resized.raw 3 512"
	@echo "PLEASE ENTER YOUR FILE NAMES AS SHOWN IN THE ABOVE EXAMPLE"
	
	
	